function test_fbipoly_bridge()
%TEST_FBIPOLY_BRIDGE Generated by Claude

    np = 0;  nf_ = 0;

    function check(name, cond)
        if cond
            np = np + 1;  fprintf('PASS  %s\n', name);
        else
            nf_ = nf_ + 1;  fprintf('FAIL  %s\n', name);
        end
    end

    fprintf('====== fbipoly layer-2 (bridge) tests ======\n\n');

    % ================================================================
    % 1. parsedesc
    % ================================================================
    fprintf('-- parsedesc --\n');

    nfF = [2 0 0; 2 1 1].';                 % 3x2 = [2 2; 0 1; 0 1]
    [no, ns, sv] = fbipoly.parsedesc(nfF);
    check('parsedesc F-like nout=2', isequal(no, 2));
    check('parsedesc F-like ns=4',   isequal(ns, 4));
    check('parsedesc F-like svlth=[2 1 1]', isequal(sv, [2 1 1]));

    [no, ns, sv] = fbipoly.parsedesc([1 2; 0 1]);
    check('parsedesc [2,1] nout=1', isequal(no, 1));
    check('parsedesc [2,1] ns=3',   isequal(ns, 3));
    check('parsedesc [2,1] svlth=[2 1]', isequal(sv, [2 1]));

    [no, ns, sv] = fbipoly.parsedesc([2 3]);   % row descriptor
    check('parsedesc row nout=2',  isequal(no, 2));
    check('parsedesc row ns=3',    isequal(ns, 3));
    check('parsedesc row svlth=3', isequal(sv, 3));

    % ================================================================
    % 2. redmonomials
    % ================================================================
    fprintf('\n-- redmonomials --\n');

    check('redmonomials([3],3) = monomials(3,3)', ...
          isequal(fbipoly.redmonomials(3,3), fbipoly.monomials(3,3)));
    check('redmonomials([4],2) = monomials(4,2)', ...
          isequal(fbipoly.redmonomials(4,2), fbipoly.monomials(4,2)));

    ref_21_1 = [1 0 0; 0 1 0; 0 0 1];
    ref_21_2 = [2 0 0; 1 1 0; 0 2 0; 1 0 1; 0 1 1; 0 0 2];
    check('redmonomials([2 1],1) ground truth', ...
          isequal(fbipoly.redmonomials([2 1],1), ref_21_1));
    check('redmonomials([2 1],2) ground truth', ...
          isequal(fbipoly.redmonomials([2 1],2), ref_21_2));

    okperm = true;
    cases  = {{[2 1],2},{[2 1],3},{[2 1 1],2},{[2 1 1],3},{[1 2],2},{[3],4}};
    for ii = 1:numel(cases)
        sv = cases{ii}{1};  k = cases{ii}{2};
        R  = fbipoly.redmonomials(sv, k);
        L  = fbipoly.monomials(sum(sv), k);
        if ~isequal(sortrows(R), sortrows(L)),  okperm = false;  end
        if size(R,1) ~= fbipoly.crd(sum(sv),k), okperm = false;  end
    end
    check('redmonomials is a permutation of monomials', okperm);

    % ================================================================
    % 3. fieldblock
    % ================================================================
    fprintf('\n-- fieldblock --\n');

    fld = struct('nvars',3,'nout',2,'coef',{cell(1,3)});
    fld.coef{3} = ones(2, fbipoly.crd(3,2));
    b2 = fbipoly.fieldblock(fld, 2);
    b1 = fbipoly.fieldblock(fld, 1);
    check('fieldblock present degree returns block', isequal(b2, fld.coef{3}));
    check('fieldblock absent degree returns zeros', ...
          isequal(b1, zeros(2, fbipoly.crd(3,1))));

    % ================================================================
    % 4. decode -- hand-built reduced-order matrix (the key test)
    % ================================================================
    fprintf('\n-- decode (reduced order, hand-built) --\n');

    nf21 = [1 2; 0 1];          % nout=1, svlth=[2 1], ns=3
    % reduced order: v0^2, v0v1, v1^2, v0v2, v1v2, v2^2
    f = [3 5 7 11 13 17];
    field = fbipoly.decode(f, nf21, [2 2]);

    % lex order monomials(3,2): v0^2, v0v1, v0v2, v1^2, v1v2, v2^2
    expect_lex = [3 5 11 7 13 17];
    check('decode stores lex-order coefficients', ...
          isequal(field.coef{3}, expect_lex));
    check('decode + evalfield gives correct value (835)', ...
          isequal(fbipoly.evalfield(field, [2 3 5]), 835));

    % ================================================================
    % 5. encode inverts decode on that example
    % ================================================================
    fprintf('\n-- encode (inverse of decode) --\n');

    check('encode recovers the reduced-order matrix', ...
          isequal(fbipoly.encode(field, nf21, [2 2]), f));

    % ================================================================
    % 6. round-trip on random data over several descriptors
    % ================================================================
    fprintf('\n-- round-trip encode(decode(.)) == identity --\n');

    rng(12345);
    descr = { ...
        {[1 3],            [1 3]}, ...
        {[2 3],            [2 2]}, ...
        {[1 2; 0 1],       [1 3]}, ...
        {[2 0 0; 2 1 1].', [1 3]}, ...
        {[2 2; 1 1; 0 1],  [1 2]} ...
    };
    okrt = true;
    for ii = 1:numel(descr)
        nfi = descr{ii}{1};
        dfi = descr{ii}{2};
        [no, nsv] = fbipoly.parsedesc(nfi);
        ncol = fbipoly.crdsum(nsv, dfi);
        fr   = randi(99, no, ncol);
        back = fbipoly.encode(fbipoly.decode(fr, nfi, dfi), nfi, dfi);
        if ~isequal(back, fr),  okrt = false;  end
    end
    check('round-trip identity on all descriptors', okrt);

    % ================================================================
    % 7. encode zero-fill, and decode recovery of the wider range
    % ================================================================
    fprintf('\n-- encode zero-fill --\n');

    fwide = fbipoly.encode(field, nf21, [1 3]);
    n1 = fbipoly.crd(3,1);  n2 = fbipoly.crd(3,2);  n3 = fbipoly.crd(3,3);
    check('encode widened column count', ...
          isequal(size(fwide,2), n1 + n2 + n3));
    check('encode zero-fills degree 1', isequal(fwide(:,1:n1), zeros(1,n1)));
    check('encode zero-fills degree 3', ...
          isequal(fwide(:, n1+n2+1:end), zeros(1,n3)));
    check('encode keeps degree 2 (reduced) intact', ...
          isequal(fwide(:, n1+1:n1+n2), f));

    field2 = fbipoly.decode(fwide, nf21, [1 3]);
    check('decode of widened recovers degree-2 block', ...
          isequal(field2.coef{3}, field.coef{3}));
    check('decode of widened has zero degree-1 block', ...
          isequal(field2.coef{2}, zeros(1,n1)));
    check('widened field evaluates the same (835)', ...
          isequal(fbipoly.evalfield(field2, [2 3 5]), 835));

    % ================================================================
    % 8. evalfield sanity on a single-subvector polynomial
    % ================================================================
    fprintf('\n-- evalfield sanity --\n');

    g.nvars = 2;  g.nout = 1;
    g.coef = { 2, [4 6], [-1 3 5] };   % 2 + 4v0 + 6v1 - v0^2 + 3v0v1 + 5v1^2
    % at (2,3): 2 + 8 + 18 - 4 + 18 + 45 = 87
    check('evalfield hand polynomial = 87', ...
          isequal(fbipoly.evalfield(g, [2 3]), 87));

    fprintf('\n====== %d passed, %d failed ======\n', np, nf_);
    if nf_ == 0
        fprintf('All layer-2 (bridge) checks passed.\n');
    end
end