function test_fbi()
%TEST_FBI, generated by Claude

    np = 0;  nf_ = 0;
    function check(name, cond)
        if cond, np=np+1; fprintf('PASS  %s\n',name);
        else,    nf_=nf_+1; fprintf('FAIL  %s\n',name); end
    end
    function fld = mkfield(nvars,nout,dmax)
        fld = struct('nvars',nvars,'nout',nout,'coef',{cell(1,dmax+1)});
    end
    function fld = setterm(fld,expo,outrow,val)   % add val * monomial(expo) to output row
        k = sum(expo);
        L = fbipoly.monomials(fld.nvars,k);
        [~,pos] = ismember(expo,L,'rows');
        if isempty(fld.coef{k+1}), fld.coef{k+1}=zeros(fld.nout,size(L,1)); end
        fld.coef{k+1}(outrow,pos) = fld.coef{k+1}(outrow,pos)+val;
    end

    fprintf('====== fbi end-to-end (PDE residual) test ======\n\n');

    % ---- problem sizes ------------------------------------------------------
    n = 1;  m = 1;  p = 1;  n_ = 2;  d = 3;     % m = p  => square solves

    % variable layout for F,H:  x(1) u(2) x_1(3) x_2(4)
    % Plant:      x' = -x + u + x_1^2
    F = mkfield(n+m+n_, n, d);
    F = setterm(F,[1 0 0 0],1,-1);     % -x
    F = setterm(F,[0 1 0 0],1, 1);     % +u
    F = setterm(F,[0 0 2 0],1, 1);     % + x_1^2   (nonlinear exo forcing)
    % Output:     y  = x - x_1
    H = mkfield(n+m+n_, p, d);
    H = setterm(H,[1 0 0 0],1, 1);     % x
    H = setterm(H,[0 0 1 0],1,-1);     % -x_1
    % Exosystem:  x_1' = x_2,  x_2' = -x_1   (harmonic oscillator)
    Fe = mkfield(n_, n_, d);
    Fe = setterm(Fe,[0 1],1, 1);       % x_1' = x_2
    Fe = setterm(Fe,[1 0],2,-1);       % x_2' = -x_1

    % ---- pack into the toolbox format (degrees 1..d) ------------------------
    nfF = [n 0 0; n m n_].';           % F descriptor used by fbi
    nhH = [p 0 0; n m n_].';
    nfe = [n_ n_];
    f  = fbipoly.encode(F,  nfF, [1 d]);
    h  = fbipoly.encode(H,  nhH, [1 d]);
    f_ = fbipoly.encode(Fe, nfe, [1 d]);

    % ---- run the solver -----------------------------------------------------
    [th, la, ff, hh] = fbi(f, h, f_, n, m, p, n_, d);

    % ---- degree-1 solution sanity (hand-derived) ---------------------------
    % H eq => T = -dH/dx_ = [1 0];  F eq => L = T + T*A_ = [1 1].
    fprintf('   th degree-1 = [%g %g]   la degree-1 = [%g %g]\n', ...
            th(1,1), th(1,2), la(1,1), la(1,2));
    check('th degree-1 = [1 0]', norm(th(:,1:n_) - [1 0]) < 1e-8);
    check('la degree-1 = [1 1]', norm(la(:,1:n_) - [1 1]) < 1e-8);

    % ---- PDE residual to degree d ------------------------------------------
    G   = [th; la; eye(n_), zeros(n_, fbipoly.crdsum(n_,[2 d]))];   % (th,la,id_x_)
    ngG = [n 0; m 0; n_ n_];

    LHS_F = fbipoly.compose(f, nfF, [1 d], G, ngG, [1 d], [1 d]);   % F(th,la,x_)
    RHS_F = fbipoly.dd(th, [n n_], [1 d], f_, nfe, [1 d], [1 d]);   % (dTH/dx_)*F_
    resF  = LHS_F - RHS_F;
    LHS_H = fbipoly.compose(h, nhH, [1 d], G, ngG, [1 d], [1 d]);   % H(th,la,x_)

    fprintf('   ||state-PDE residual||  = %.3e\n', norm(resF(:)));
    fprintf('   ||output residual||     = %.3e\n', norm(LHS_H(:)));
    check('state PDE residual ~ 0', norm(resF(:)) < 1e-8);
    check('output residual ~ 0',    norm(LHS_H(:)) < 1e-8);

    % ---- shapes of the transformed plant/output ----------------------------
    ncol = fbipoly.crdsum(n+m+n_, [1 d]);
    check('ff has shape N x crdsum',  isequal(size(ff), [n, ncol]));
    check('hh has shape P x crdsum',  isequal(size(hh), [p, ncol]));

    % On the manifold z=v=0, the transformed output equals H(th,la,x_) (~0):
    % restrict hh to the x_ variables by composing with (0,0,x_).
    idx_  = [eye(n_), zeros(n_, fbipoly.crdsum(n_,[2 d]))];      % x_ -> x_
    zero_ = zeros(n+m, fbipoly.crdsum(n_,[1 d]));                % z,v -> 0
    gman  = [zero_; idx_];                                      % (z,v,x_) <- (0,0,x_)
    z0 = fbipoly.compose(hh, nhH, [1 d], gman, [n 0; m 0; n_ n_], [1 d], [1 d]);
    check('hh restricted to manifold ~ 0', norm(z0(:)) < 1e-8);

    fprintf('\n====== %d passed, %d failed ======\n', np, nf_);
    if nf_==0, fprintf('All FBI end-to-end checks passed.\n'); end
end