function test_fbipoly_dd()
%TEST_FBIPOLY_DD Generated by Claude

    np = 0;  nf_ = 0;
    function check(name, cond)
        if cond, np=np+1; fprintf('PASS  %s\n',name);
        else,    nf_=nf_+1; fprintf('FAIL  %s\n',name); end
    end
    function fld = randfield(nvars,nout,d0,d1)
        fld = struct('nvars',nvars,'nout',nout,'coef',{cell(1,d1+1)});
        for k=d0:d1, fld.coef{k+1}=randi([-3 3],nout,fbipoly.crd(nvars,k)); end
    end
    function G = idfield(ns)        % identity vector field G_j = x_j (degree 1)
        G = struct('nvars',ns,'nout',ns,'coef',{{[], eye(ns)}});
    end

    fprintf('====== fbipoly layer-4 (dd / prt) tests ======\n\n');

    % ================================================================
    % 1. partialfield
    % ================================================================
    fprintf('-- partialfield --\n');

    % P = x0^2 x1 + 3 x1^3   (2 vars).  monomials(2,3)=[3 0;2 1;1 2;0 3]
    P = struct('nvars',2,'nout',1,'coef',{{[],[],[],[0 1 0 3]}});
    d0 = fbipoly.partialfield(P,1);   % d/dx0 = 2 x0 x1     -> deg2 [0 2 0]
    d1 = fbipoly.partialfield(P,2);   % d/dx1 = x0^2 + 9x1^2-> deg2 [1 0 9]
    check('partialfield d/dx0', isequal(d0.coef{3}, [0 2 0]));
    check('partialfield d/dx1', isequal(d1.coef{3}, [1 0 9]));

    % ================================================================
    % 2. ddmul via Euler's identity
    % ================================================================
    fprintf('\n-- ddmul (Euler) --\n');

    rng(3);
    okhom = true;
    for t=1:15
        ns=randi([1 4]); nout=randi([1 3]); k=randi([1 4]);
        Ph = struct('nvars',ns,'nout',nout,'coef',{cell(1,k+1)});
        Ph.coef{k+1}=randi([-3 3],nout,fbipoly.crd(ns,k));
        H = fbipoly.ddmul(Ph, idfield(ns), k);
        if ~isequal(H.coef{k+1}, k*Ph.coef{k+1}), okhom=false; end
    end
    check('ddmul(P,id) = k*P for homogeneous P', okhom);

    okmix = true;
    for t=1:10
        ns=randi([1 3]); nout=randi([1 2]);
        Pm = randfield(ns,nout,1,3);
        H  = fbipoly.ddmul(Pm, idfield(ns), 3);
        for k=1:3
            if ~isequal(fbipoly.fieldblock(H,k), k*Pm.coef{k+1}), okmix=false; end
        end
    end
    check('ddmul(P,id) = sum k*P_k for mixed-degree P', okmix);

    % hand example: F=x0^2, G=(x1,x0) -> dF/dx0*x1 = 2 x0 x1
    F = struct('nvars',2,'nout',1,'coef',{{[],[],[1 0 0]}});  % x0^2
    G = struct('nvars',2,'nout',2,'coef',{{[],[0 1; 1 0]}});  % g0=x1, g1=x0
    H = fbipoly.ddmul(F,G,3);
    check('ddmul hand deg2 = [0 2 0]', isequal(H.coef{3}, [0 2 0]));
    check('ddmul hand evaluates to 12 at (2,3)', isequal(fbipoly.evalfield(H,[2 3]),12));

    % ================================================================
    % 3. dd descriptor path (FBI-style eye(n_k) operator)
    % ================================================================
    fprintf('\n-- dd (descriptor, Lie operator) --\n');

    okdd = true;
    for cs = {[2 2],[2 3],[3 2]}
        nbar = cs{1}(1);  k = cs{1}(2);
        nk = fbipoly.crd(nbar,k);
        L = fbipoly.dd(eye(nk), [nk nbar], k, eye(nbar), [nbar nbar], 1, k);
        if ~isequal(L, k*eye(nk)), okdd = false; end
    end
    check('dd(eye(n_k),..,eye(n_),1,k) = k*eye(n_k)', okdd);

    % ================================================================
    % 4. prt
    % ================================================================
    fprintf('\n-- prt --\n');

    rng(9);
    nf = [1 2; 0 1];               % svlth=[2 1], ns=3, nout=1
    ns = 3;
    f  = randi(50, 1, fbipoly.crdsum(ns,[1 3]));   % degrees 1..3
    check('prt identity range returns f', isequal(fbipoly.prt(f,nf,[1 3],[1 3]), f));

    n1=fbipoly.crd(ns,1); n2=fbipoly.crd(ns,2); n3=fbipoly.crd(ns,3);
    check('prt extracts degree-2 block', ...
          isequal(fbipoly.prt(f,nf,[1 3],[2 2]), f(:, n1+1:n1+n2)));
    f12  = randi(50, 1, fbipoly.crdsum(ns,[1 2]));  % a field spanning degrees 1..2
    wide = fbipoly.prt(f12,nf,[1 2],[1 3]);         % widen beyond df -> zero-fill deg3
    check('prt widening keeps low degrees', ...
          isequal(wide(:,1:n1+n2), f12));
    check('prt widening zero-fills degree 3', isequal(wide(:,n1+n2+1:end), zeros(1,n3)));

    fprintf('\n====== %d passed, %d failed ======\n', np, nf_);
    if nf_==0, fprintf('All layer-4 (dd / prt) checks passed.\n'); end
end