function test_fbipoly_core()
%TEST_FBIPOLY_CORE, generated by Claude
    np = 0;          % number passed
    nf = 0;          % number failed

    % nested helper: record a boolean check
    function check(name, cond)
        if cond
            np = np + 1;
            fprintf('PASS  %s\n', name);
        else
            nf = nf + 1;
            fprintf('FAIL  %s\n', name);
        end
    end

    fprintf('====== fbipoly layer-1 tests ======\n\n');

    % ================================================================
    % 1. binom
    % ================================================================
    fprintf('-- binom --\n');

    check('binom(5,2)=10',    isequal(fbipoly.binom(5,2), 10));
    check('binom(5,0)=1',     isequal(fbipoly.binom(5,0), 1));
    check('binom(5,5)=1',     isequal(fbipoly.binom(5,5), 1));
    check('binom(5,6)=0',     isequal(fbipoly.binom(5,6), 0));   % b>a -> 0
    check('binom(5,-1)=0',    isequal(fbipoly.binom(5,-1), 0));  % b<0 -> 0
    check('binom(0,0)=1',     isequal(fbipoly.binom(0,0), 1));
    check('binom(-1,0)=1',    isequal(fbipoly.binom(-1,0), 1));  % crd(0,0) case

    % Agreement with base nchoosek over a grid of a>=b>=0.
    ok = true;
    for a = 0:12
        for b = 0:a
            if fbipoly.binom(a,b) ~= nchoosek(a,b)
                ok = false;
            end
        end
    end
    check('binom matches nchoosek on 0<=b<=a<=12', ok);

    % Vectorized call (array inputs, broadcasting).
    av = [5 6 7];
    bv = [2 3 0];
    check('binom vectorized', isequal(fbipoly.binom(av,bv), [10 20 1]));
    check('binom scalar+array broadcast', ...
          isequal(fbipoly.binom(6,[0 1 2 3]), [1 6 15 20]));

    % ================================================================
    % 2. crd
    % ================================================================
    fprintf('\n-- crd --\n');

    check('crd(1,4)=1',  isequal(fbipoly.crd(1,4), 1));     % x0^4 only
    check('crd(2,0)=1',  isequal(fbipoly.crd(2,0), 1));     % constant
    check('crd(2,1)=2',  isequal(fbipoly.crd(2,1), 2));     % x0,x1
    check('crd(2,2)=3',  isequal(fbipoly.crd(2,2), 3));
    check('crd(3,3)=10', isequal(fbipoly.crd(3,3), 10));
    check('crd(0,0)=1',  isequal(fbipoly.crd(0,0), 1));
    check('crd(0,1)=0',  isequal(fbipoly.crd(0,1), 0));

    % n given as a vector is summed (toolbox semantics).
    check('crd([2 1],2)=crd(3,2)', isequal(fbipoly.crd([2 1],2), fbipoly.crd(3,2)));

    % crd(n,k) must equal C(n+k-1,k) for n>=1.
    ok = true;
    for n = 1:6
        for k = 0:6
            if fbipoly.crd(n,k) ~= nchoosek(n+k-1, k)
                ok = false;
            end
        end
    end
    check('crd matches C(n+k-1,k) for 1<=n<=6, 0<=k<=6', ok);

    % ================================================================
    % 3. crdsum
    % ================================================================
    fprintf('\n-- crdsum --\n');

    check('crdsum(2,[0 1])=3', isequal(fbipoly.crdsum(2,[0 1]), 3));
    check('crdsum(2,[1 2])=5', isequal(fbipoly.crdsum(2,[1 2]), 5));
    check('crdsum scalar d acts as [d d]', ...
          isequal(fbipoly.crdsum(3,2), fbipoly.crd(3,2)));

    % crdsum over a range equals the sum of crd over that range.
    ok = true;
    for n = 0:6
        for d0 = 0:4
            for d1 = d0:5
                lhs = fbipoly.crdsum(n,[d0 d1]);
                rhs = 0;
                for k = d0:d1
                    rhs = rhs + fbipoly.crd(n,k);
                end
                if lhs ~= rhs
                    ok = false;
                end
            end
        end
    end
    check('crdsum equals sum of crd over the degree range', ok);

    % ================================================================
    % 4. monomials
    % ================================================================
    fprintf('\n-- monomials --\n');

    % Exact references (these define the required toolbox column order).
    ref_2_2 = [2 0; 1 1; 0 2];
    ref_2_3 = [3 0; 2 1; 1 2; 0 3];
    ref_3_3 = [3 0 0; 2 1 0; 2 0 1; 1 2 0; 1 1 1; ...
               1 0 2; 0 3 0; 0 2 1; 0 1 2; 0 0 3];

    check('monomials(2,2) order', isequal(fbipoly.monomials(2,2), ref_2_2));
    check('monomials(2,3) order', isequal(fbipoly.monomials(2,3), ref_2_3));
    check('monomials(3,3) order', isequal(fbipoly.monomials(3,3), ref_3_3));

    % Degenerate cases.
    check('monomials(3,0) = zeros(1,3)', isequal(fbipoly.monomials(3,0), zeros(1,3)));
    check('monomials(1,4) = 4',          isequal(fbipoly.monomials(1,4), 4));
    check('monomials(4,1) = eye(4)',     isequal(fbipoly.monomials(4,1), eye(4)));
    check('monomials(0,0) = zeros(1,0)', isequal(fbipoly.monomials(0,0), zeros(1,0)));

    % Structural invariants over a grid.
    ok_count = true; ok_sum = true; ok_uniq = true; ok_size = true;
    for n = 1:5
        for k = 0:5
            E = fbipoly.monomials(n,k);
            if size(E,1) ~= fbipoly.crd(n,k),         ok_count = false; end
            if size(E,2) ~= n,                        ok_size  = false; end
            if k > 0 && any(sum(E,2) ~= k),           ok_sum   = false; end
            if size(unique(E,'rows'),1) ~= size(E,1), ok_uniq  = false; end
        end
    end
    check('monomials row count = crd(n,k)',  ok_count);
    check('monomials has n columns',         ok_size);
    check('monomials rows sum to k',         ok_sum);
    check('monomials rows are unique',       ok_uniq);

    % Cross-check: stacking degrees d0..d1 gives crdsum(n,[d0 d1]) rows.
    ok = true;
    for n = 1:5
        for d0 = 0:3
            for d1 = d0:4
                tot = 0;
                for k = d0:d1
                    tot = tot + size(fbipoly.monomials(n,k),1);
                end
                if tot ~= fbipoly.crdsum(n,[d0 d1])
                    ok = false;
                end
            end
        end
    end
    check('stacked monomial counts match crdsum', ok);

    % ================================================================
    % summary
    % ================================================================
    fprintf('\n====== %d passed, %d failed ======\n', np, nf);
    if nf == 0
        fprintf('All layer-1 checks passed.\n');
    end
end