function test_fbipoly_compose()
%TEST_FBIPOLY_COMPOSE Generated by Claude

    np = 0;  nf_ = 0;
    function check(name, cond)
        if cond, np = np + 1;  fprintf('PASS  %s\n', name);
        else,    nf_ = nf_ + 1;  fprintf('FAIL  %s\n', name);  end
    end
    function fld = randfield(nvars, nout, d0, d1)
        fld = struct('nvars',nvars,'nout',nout,'coef',{cell(1,d1+1)});
        for k = d0:d1
            fld.coef{k+1} = randi([-3 3], nout, fbipoly.crd(nvars,k));
        end
    end

    fprintf('====== fbipoly layer-3 (compose) tests ======\n\n');

    % ================================================================
    % 1. polymul
    % ================================================================
    fprintf('-- polymul --\n');

    % hand example: (1 + x0)^2 = 1 + 2 x0 + x0^2  (in 2 variables)
    P = struct('nvars',2,'nout',1,'coef',{{1, [1 0]}});   % 1 + x0
    R = fbipoly.polymul(P, P, 2);
    check('polymul (1+x0)^2 deg0', isequal(R.coef{1}, 1));
    check('polymul (1+x0)^2 deg1', isequal(R.coef{2}, [2 0]));
    check('polymul (1+x0)^2 deg2', isequal(R.coef{3}, [1 0 0]));  % x0^2 only

    % semantic: evaluate P*Q == evalfield(P).*evalfield(Q) at integer points
    rng(7);
    okmul = true;
    for t = 1:20
        n = randi([1 3]);
        A = randfield(n, 1, 0, randi([0 3]));
        B = randfield(n, 1, 0, randi([0 3]));
        dmax = (numel(A.coef)-1) + (numel(B.coef)-1);   % no truncation
        AB = fbipoly.polymul(A, B, dmax);
        x = randi([-2 2], 1, n);
        if fbipoly.evalfield(AB, x) ~= fbipoly.evalfield(A,x) * fbipoly.evalfield(B,x)
            okmul = false;
        end
    end
    check('polymul value = product of values (random)', okmul);

    % truncation: keep only degrees <= dmax of (1+x0)^3
    P3full = fbipoly.polymul(fbipoly.polymul(P,P,3), P, 3);  % 1+3x0+3x0^2+x0^3
    P3trunc = fbipoly.polymul(fbipoly.polymul(P,P,1), P, 1); % keep deg<=1: 1+2x0 then *P trunc1
    check('polymul truncation drops high degrees', ...
          numel(P3trunc.coef) <= 2 || isempty(P3trunc.coef{3}));
    check('polymul (1+x0)^3 deg3 coef = 1', isequal(P3full.coef{4}, [1 0 0 0]));

    % ================================================================
    % 2. composecore
    % ================================================================
    fprintf('\n-- composecore --\n');

    % hand example: F(t0,t1) = t0^2 + t1,  G = (y, y^2)  =>  H = 2 y^2
    F = struct('nvars',2,'nout',1,'coef',{{[], [0 1], [1 0 0]}}); % t1 + t0^2
    G = struct('nvars',1,'nout',2,'coef',{{[], [1;0], [0;1]}});   % g0=y, g1=y^2
    H = fbipoly.composecore(F, G, 2);
    check('composecore hand: H(y)=2y^2 at y=3 (=18)', ...
          isequal(fbipoly.evalfield(H,3), 18));
    check('composecore hand: deg2 coef = 2', isequal(H.coef{3}, 2));

    % semantic random (G has NO constant term)
    rng(11);
    okc = true;
    for t = 1:15
        m = randi([1 3]);  n = randi([1 3]);  nout = randi([1 2]);
        dF = randi([1 3]);  dG = randi([1 2]);
        Ff = randfield(m, nout, 1, dF);
        Gg = randfield(n, m, 1, dG);
        dmax = dF * dG;                          % upper bound -> exact
        Hh = fbipoly.composecore(Ff, Gg, dmax);
        y  = randi([-2 2], 1, n);
        gy = fbipoly.evalfield(Gg, y);           % m x 1 intermediate
        if ~isequal(fbipoly.evalfield(Hh, y), fbipoly.evalfield(Ff, gy))
            okc = false;
        end
    end
    check('composecore H(y)=F(G(y)) (random, no constant in G)', okc);

    % semantic random (G HAS a constant term -> general case)
    rng(13);
    okcc = true;
    for t = 1:15
        m = randi([1 3]);  n = randi([1 3]);  nout = randi([1 2]);
        dF = randi([1 3]);  dG = randi([1 2]);
        Ff = randfield(m, nout, 0, dF);
        Gg = randfield(n, m, 0, dG);             % includes degree-0
        dmax = dF * dG;
        Hh = fbipoly.composecore(Ff, Gg, dmax);
        y  = randi([-2 2], 1, n);
        gy = fbipoly.evalfield(Gg, y);
        if ~isequal(fbipoly.evalfield(Hh, y), fbipoly.evalfield(Ff, gy))
            okcc = false;
        end
    end
    check('composecore H(y)=F(G(y)) (random, constant in G)', okcc);

    % ================================================================
    % 3. compose (descriptor wrapper)
    % ================================================================
    fprintf('\n-- compose (descriptor wrapper) --\n');

    % (a) single subvector: F=t0^2+t1, g0=y, g1=y^2, substitute t<-g
    f  = [0 1 1 0 0];          % F over 2 vars, df=[1 2]: deg1 [0 1], deg2 [1 0 0]
    nf = [1 2];                % nout=1, f inputs = one subvector of size 2
    g  = [1 0; 0 1];           % g0=y (deg1), g1=y^2 (deg2)
    ng = [2 1];                % g outputs [2] aligned to f inputs; g inputs [1]
    [h, nh] = fbipoly.compose(f, nf, [1 2], g, ng, [1 2], [1 2]);
    check('compose (a) nh = [1 1]', isequal(nh, [1 1]));
    check('compose (a) h = [0 2]',  isequal(h, [0 2]));
    fieldh = fbipoly.decode(h, nh, [1 2]);
    check('compose (a) evaluates to 18 at y=3', ...
          isequal(fbipoly.evalfield(fieldh, 3), 18));   % 2*3^2

    % (b) MULTI-subvector (forces reduced-order decode of f):
    %     f(x0,x1,u0) = x0 + x1*u0, subvectors x=[2], u=[1];
    %     substitute x0=y, x1=y^2, u0=y  =>  H = y + y^3.
    nf2 = [1 2; 0 1];          % nout=1, svlth=[2 1], ns=3
    % f in REDUCED order: deg1 [x0 x1 u0]=[1 0 0]; deg2 [x0^2 x0x1 x1^2 x0u0 x1u0 u0^2]
    f2  = [1 0 0,  0 0 0 0 1 0];     % x0 + x1*u0
    ng2 = [2 1; 1 0];          % g outputs [2;1]=f inputs; g inputs [1;0] -> ns=1
    g2  = [1 0; 0 1; 1 0];     % rows: x0=y, x1=y^2, u0=y
    [h2, nh2] = fbipoly.compose(f2, nf2, [1 2], g2, ng2, [1 2], [1 3]);
    check('compose (b) nh = [1 1;0 0]', isequal(nh2, [1 1; 0 0]));
    check('compose (b) h = [1 0 1] (y + y^3)', isequal(h2, [1 0 1]));
    fieldh2 = fbipoly.decode(h2, nh2, [1 3]);
    check('compose (b) evaluates to 10 at y=2', ...
          isequal(fbipoly.evalfield(fieldh2, 2), 10));   % 2 + 2^3

    % (c) alignment guard fires on mismatch
    errfired = false;
    try
        fbipoly.compose(f, [1 2], [1 2], g, [3 1], [1 2], [1 2]); % g-out 3 != f-in 2
    catch
        errfired = true;
    end
    check('compose rejects mismatched alignment', errfired);

    % ================================================================
    fprintf('\n====== %d passed, %d failed ======\n', np, nf_);
    if nf_ == 0, fprintf('All layer-3 (compose) checks passed.\n'); end
end